FROM microsoft/dotnet:2.0-runtime-nanoserver AS base
WORKDIR /app

FROM microsoft/dotnet:2.0-sdk-nanoserver AS build
WORKDIR /src
COPY HelloWorld.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HelloWorld.dll"]
